### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by xsc** [stalefruits/gniazdo#19]
## Current status of http_proxy support in Gniazdo

As of 11/2016, it is not supported in gniazdo due to limitations of Jetty 9 (see eclipse/jetty.project#117). It seems they plan to fix it in Jetty 9.4.x.

However, you can use [gniazdo-jsr356](https://github.com/stylefruits/gniazdo-jsr356) instead of Gniazdo. It has outwardly the same API but internally it uses the standard Java EE websockets API and its Tyrus implementation (while also supporting Jetty). Tyrus does support http_proxy (and other settings).

More discussion can be found in #16.

**Comment by jeffb-stell** [comment]
It appears Jetty 9.4.6 has been released, with proxy support. Are there plans to update gniazdo to pull it in?

**Comment by jakubholynet** [comment]
Is there going to be a new release with Jetty 9.4.6. anytime soon, @jstepien ? Thanks!

**Comment by jstepien** [comment]
Sure, I've just pushed https://clojars.org/stylefruits/gniazdo/versions/1.1.0 with websocket-client 9.4.12.v20180830.

**Comment by jstepien** [comment]
HTTP proxy configuration has been linked in in 62585ac4e6a777e08a2635445587f9062a89405b.
