### ISSUE TITLE
Async nature of websockets

### ISSUE THREAD

**Issue by astoeckley** [stalefruits/gniazdo#27]
Quick question, if you know. Does the websocket listener run in a background thread, and if it does, is it calling my receiving functions also on another thread, or does it dispatch directly to the main thread? I'm trying to understand what, if any, consideration I should have for asynchronous activity when processing socket messages, since it is important I process them in the order they are received.

**Comment by jstepien** [comment]
Hi Andrew. I think that all your callbacks are invoked in dedicated 
listener threads. Your main thread remains unaffected. Writing a small 
test verifying it shouldn't be difficult.

How many listener threads are there is an open question; I'd recommend 
consulting Jetty's documentation.

If the order of processing messages matters, I'd recommend you have your 
callbacks put messages on a queue and then consume them in a dedicated 
thread you control. A queue could be a for instance a 
ConcurrentLinkedQueue, a core.async channel, or a 
clojure.lang.PersistentQueue in an atom.

Let me know if it helps.

**Comment by astoeckley** [comment]
Thanks, I was leaning to using core.async channel for immediately dumping all socket responses. Your suggestion is enough to persuade me to do so, thanks!
