### ISSUE TITLE
Turn off logging of all incoming messages

### ISSUE THREAD

**Issue by astoeckley** [stalefruits/gniazdo#28]
All incoming socket messages are logged to the repl (if running lein repl) or to nrepl in my case, when using cider. I'm wondering if there is a way to turn that off? Logging is a time-consuming activity and I have a hunch it is responsible for some latency in my app, since I can't find any latency when timing things in my code. Plus it would just be nice not to see all the bytes streaming by.

**Comment by mknoszlig** [comment]
Hi there,

to the best of my knowledge, gniazdo doesn't do any logging itself, so what you're seeing are most likely logs produced by the underlying jetty websocket client. A quick search produced the following link: https://www.eclipse.org/jetty/documentation/9.4.x/configuring-logging.html
Depending on what it is exactly you're seeing, it should be sufficient to add the appropriate logging configuration to your project resources so jetty can pick it up and behave as desired.

Let me know if that works.

Cheers

**Comment by astoeckley** [comment]
Well, I've been looking at that link's info for about half an hour and can't figure it out. Probably because I have nearly zero JVM or Java experience outside writing raw Clojure code. Would be nice if there was an easy way to control this kind of JVM activity from a simple setting in project.clj.

**Comment by mknoszlig** [comment]
I agree that logging on the JVM can be quite opaque, especially for those who don't already have a complementary background. However, I'm afraid this would exceed the scope of gniazdo (a mere websocket library) and would better be solved as eg a lein plugin.

Here's one thing that i tried toying around with the gniazdo repo that let me turn off all jetty related logging:
1. in your project, create a file `resources/jetty-logging.properties`
2. add the following content:
```
## Force jetty logging implementation
org.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog

## Set logging levels from: ALL, DEBUG, INFO, WARN, OFF
org.eclipse.jetty.LEVEL=OFF
```
3. restart your app (the property files are loaded at startup)

Hopefully this will work for you as well.

Cheers

**Comment by astoeckley** [comment]
Thanks very much for the help. I created the file, put it in resources/ and added this line to my `project.clj`:

`:resource-paths ["resources/"]`

I restarted CIDER, but I still see stuff like this for every incoming socket message:

```
[Raw read (bb)]: length = 57
0000: 17 03 03 00 34 02 B8 7D   C0 84 6C DD 8A 83 8F F3  ....4.....l.....
0010: F6 E5 5E D1 75 71 07 96   9C 9B F0 FD 3E 39 8A 73  ..^.uq......>9.s
0020: 2C 6F 98 79 E8 75 98 25   B2 42 4C ED 01 8D D2 00  ,o.y.u.%.BL.....
0030: D1 B8 DD 24 18 12 EF BE   4E                       ...$....N
Padded plaintext after DECRYPTION:  len = 28
0000: E2 06 19 0A 0D 70 69 6E   67 2D 72 65 73 70 6F 6E  .....ping-respon
0010: 73 65 10 D6 B4 95 37 18   D4 BC 95 37              se....7....7
 o o
```

Since some of the messages are quite big, this results in a gigantic amount of onscreen logging, which I assume it was is slowing down the app.

**Comment by mknoszlig** [comment]
This is just a guess, but are you by chance running your JVM with `-Djavax.net.debug=all` or something similar? If so, you might want to try removing it.
Your logs look quite similar to what one might use to debug SSL/TLS connections: https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html

**Comment by astoeckley** [comment]
**_Wow!_**

You nailed it. What a guess! I did indeed have that turned on, but not something I added to the project.clj, was already there. I assumed it was benign -- obviously not!

Thanks for the help! Definitely solved it. I've been trying all sorts of stuff for 2 days on this. Sheesh.

Thanks man!
