### ISSUE TITLE
Text message size [146765] exceeds maximum size [65536]

### ISSUE THREAD

**Issue by bertofer** [stalefruits/gniazdo#30]
Hi, I have the error mentioned in the title. I looked for that error in Jetty in google, and found that there's a function `setMaxTextMessageBufferSize` that could be used in the policy of the websocket client to increase this size, but it didn't work.

I am quite new to java interop, so if there is any mistake, please correct me. 

Does anyone know how to solve it?

This is the code I'm currently using, taken from different ns

```clojure
(defprotocol IWebSocketActions
  (connect [this] [this wsclient])
  (send-msg [this msg])
  (close [this]))

(defrecord WebSocketClient [url conn handlers]
  IWebSocketActions
  (connect [this]
    (let [new-conn (apply ws/connect url (flatten (into [] handlers)))]
      (reset! conn new-conn)))
  (connect [this wsclient]
    (println (flatten (into [:client wsclient] handlers)))
    (let [new-conn (apply ws/connect url (flatten (into [:client wsclient] handlers)))]
      (reset! conn new-conn)))
  (send-msg [this msg]
    (when-let [wsc @conn]
      (ws/send-msg wsc (json/generate-string msg))))
  (close [this]
    (ws/close @conn)
    (reset! conn nil)))

(def client (ws/map->WebSocketClient {:url bitmex-url
                                      :conn (atom nil)
                                      :handlers handlers}))

(def ws-client (let [client (websocket/client (new URI bitmex-url))]
                           (.setMaxTextMessageBufferSize (.getPolicy client) Integer/MAX_VALUE)
                           (.start client)
                            client))

(ws/connect client ws-client)
;; (ws/close client)
(ws/send-msg client {:op "subscribe", :args ["orderBookL2:XBTUSD"]})
```

The handlers is just a map, and the connect works properly, and with small messages also works fine.

**Comment by bertofer** [comment]
Thanks @mknoszlig ! Yeah everything was just using `setMaxTextMessageSize`

**Comment by mknoszlig** [comment]
Glad to help! A quick observation: `Integer/MAX_VALUE` seems like it's too loose (that's a lot of bytes for a websocket message), this may come back to haunt you when you least expect it. I'd prefer a value that's a bit more conservative.

Cheers!
