### ISSUE TITLE
Custom WebSocketClients require manual stop

### ISSUE THREAD

**Issue by IGJoshua** [stalefruits/gniazdo#33]
After working with the websockets for a while, I noticed that in order to create a websocket with an adequate buffer size, I have to manually create a websocket client (or use the provided `client` function from gniazdo), but when I close the websocket, that client isn't stopped. That may be intended behavior, but the result is that it keeps applications alive after all other non-daemon threads have stopped, and it's difficult to determine the reason because it's not mentioned in the documentation.

I'd love to see the documentation related to the `client` function specify that the client must have `.stop` called on it in order to exit the application.

**Comment by jstepien** [comment]
Hey, thanks for filing the issue. I'd be happy to merge a patch adjusting the documentation as you outlined.
